### ISSUE TITLE
Getting error "Null check operator used on a null value" 

### ISSUE THREAD

**Issue by bobmoff** [carlosfiori/dart-auto-const#5]
Cant run it. Getting error ..

```
Unhandled exception:
Null check operator used on a null value
#0      analyzeAndAddConsts (file:///Users/bobmoff/.pub-cache/hosted/pub.dev/auto_const-1.0.1+1/bin/auto_const.dart:76:35)
#1      main (file:///Users/bobmoff/.pub-cache/hosted/pub.dev/auto_const-1.0.1+1/bin/auto_const.dart:30:9)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by mramoreira** [comment]
Same problem, after upgrading to last version of Flutter.
